<a href="https://colab.research.google.com/github/UtkarshAIITB/DAV-Team-Assignment/blob/main/Q3_with_additional_feature.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Importing the data

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DAV_assignment/comment-toxicity-classification-ques /train.csv')
train.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [ ]:
train.shape

(159571, 8)

## Analysing the data

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             159571 non-null  object
 1   comment_text   159571 non-null  object
 2   toxic          159571 non-null  int64
 3   severe_toxic   159571 non-null  int64
 4   obscene        159571 non-null  int64
 5   threat         159571 non-null  int64
 6   insult         159571 non-null  int64
 7   identity_hate  159571 non-null  int64
dtypes: int64(6), object(2)
memory usage: 9.7+ MB

In [ ]:
train.describe()
# !alert = low mean values

,toxic,severe_toxic,obscene,threat,insult,identity_hate
count,159571.000000,159571.000000,159571.000000,159571.000000,159571.000000,159571.000000
mean,0.095844,0.009996,0.052948,0.002996,0.049364,0.008805
std,0.294379,0.099477,0.223931,0.054650,0.216627,0.093420
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
for i in range(0, train.shape[0]):
  if( (train.loc[i, 'toxic'] == 0) & (train.loc[i, 'severe_toxic'] == 0) & (train.loc[i, 'obscene'] == 0) & (train.loc[i, 'threat'] == 0) & (train.loc[i, 'insult'] == 0) & (train.loc[i, 'identity_hate'] == 0)):
    train.loc[i, 'Non-toxic'] = 1
  else:
    train.loc[i, 'Non-toxic'] = 0

In [ ]:
for columns in train.columns[2:]:
  print(columns + ' : count : ' + str(train[columns].sum()))

toxic : count : 15294
severe_toxic : count : 1595
obscene : count : 8449
threat : count : 478
insult : count : 7877
identity_hate : count : 1405
Non-toxic : count : 143346.0

The count values depict that out of total training set of 1,59,571 rows, very less of them are actually labelled in any of the categories.

In [ ]:
columns = ['Trait', 'Count']
wow = pd.DataFrame(columns = columns)
for columns in train.columns[2:]:
  wow = wow.append({'Trait': columns, 'Count':train[columns].sum()}, ignore_index = True)

In [ ]:
wow

           Trait     Count
0          toxic     15294
1   severe_toxic      1595
2        obscene      8449
3         threat       478
4         insult      7877
5  identity_hate      1405
6      Non-toxic  143346.0

In [ ]:
import plotly.express as px
fig = px.bar(wow, x='Trait', y='Count')
fig.show()

In [ ]:
# the data is highly unbiased towards non-toxic or non classified content

Unbiasing the data by dropping 80% of rows with 'Non-toxic' = 1 to create a more balanced dataset

In [ ]:
train_b = train.drop(train[train['Non-toxic'] == 1].sample(frac=0.8).index)

In [ ]:
for columns in train_b.columns[2:]:
  print(columns + ' : count : ' + str(train_b[columns].sum()))

toxic : count : 15294
severe_toxic : count : 1595
obscene : count : 8449
threat : count : 478
insult : count : 7877
identity_hate : count : 1405
Non-toxic : count : 28669.0

In [ ]:
new = train_b.drop(columns = 'id')
new.head(3)

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,Non-toxic
5,"""\n\nCongratulations from me as well, use the ...",0,0,0,0,0,0,1.0
6,COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK,1,1,1,0,1,0,0.0
8,Sorry if the word 'nonsense' was offensive to ...,0,0,0,0,0,0,1.0

In [ ]:
new = new.reset_index(drop = True)
new.head()

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,Non-toxic
0,"""\n\nCongratulations from me as well, use the ...",0,0,0,0,0,0,1.0
1,COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK,1,1,1,0,1,0,0.0
2,Sorry if the word 'nonsense' was offensive to ...,0,0,0,0,0,0,1.0
3,Hey... what is it..\n@ | talk .\nWhat is it......,1,0,0,0,0,0,0.0
4,"Bye! \n\nDon't look, come or think of comming ...",1,0,0,0,0,0,0.0

In [ ]:
Y = new.iloc[:,1:]
Y.head()

   toxic  severe_toxic  obscene  threat  insult  identity_hate  Non-toxic
0      0             0        0       0       0              0        1.0
1      1             1        1       0       1              0        0.0
2      0             0        0       0       0              0        1.0
3      1             0        0       0       0              0        0.0
4      1             0        0       0       0              0        0.0

In [ ]:
import re
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
import sys
print(sys.getrecursionlimit())

1000

In [ ]:
sys.setrecursionlimit(5000)

In [ ]:
def clean_text(df):
    all_reviews = list()
    lines = df["comment_text"].values.tolist()
    for text in lines:
        text = text.lower()
        pattern = re.compile('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
        text = pattern.sub('', text)
        text = re.sub(r"[,.\"!@#$%^&*(){}?/;`~:<>+=-]", "", text)
        tokens = word_tokenize(text)
        table = str.maketrans('', '', string.punctuation)
        stripped = [w.translate(table) for w in tokens]
        words = [word for word in stripped if word.isalpha()]
        stop_words = set(stopwords.words("english"))
        stop_words.discard("not")
        PS = PorterStemmer()
        words = [PS.stem(w) for w in words if not w in stop_words]
        words = ' '.join(words)
        all_reviews.append(words)
    return all_reviews

In [ ]:
all_comments = clean_text(train_b)

In [ ]:
all_comments[0:20]

['congratul well use tool well talk',
 'cocksuck piss around work',
 'sorri word nonsens offens anyway not intend write anyth articlewow would jump vandal mere request encycloped one use school refer select breed page almost stub point anim breed short messi articl give info must someon around expertis eugen',
 'hey talk exclus group wp talibanswho good destroy selfappoint purist gang one ask question abt antisoci destruct noncontribut wp ask sityush clean behavior issu nonsens warn',
 'bye nt look come think com back tosser',
 'mitsurugi point made sens not argu includ hindi ryo sakazaki page includ inform',
 'need apolog wikipedia articl made reconcil knowledg subject differ sourc done histori studi not archaeolog studi guess could scan page email could ask someon translat page',
 'not make straw man argument never claim odonohu posit rather practition research field ignor dsm posit exactli quot say also someth odonohu agre combat notion absurd part claim pedophilia sexual orient sinc mani research hold posit would unfair call absurd disord part divid field argu not disord end day valu judgment cantor point earlier thread not scientif judgement choos make valu judgment articl state clearli not pretend scientif basi',
 'hi explicit block fenian editwar giant causeway wp made sever edit describ terror',
 'sure lead must briefli summar armenia histori simpli ad found necessari anyon think sentenc redund lead welcom remov make edit talk',
 'gay antisemmitian archangel white tiger meow greetingshhh uh two way eras comment holocaust brutal slay jew not gaysgypsysslavsanyon antisemitian shave head bald go skinhead meet doubt word bibl homosexu deadli sin make pentagram tatoo forehead go satanist mass gay pal first last warn fuck gay wo nt appreci nazi shwain would write page nt wish talk anymor bewar dark side',
 'fuck filthi mother ass dri',
 'sorri sorri screw around someon talk page bad know templat talk page help assert domin know bow almighti administr go go play outsidewith mom',
 'point ammend appropri encycloped notabilitysignific',
 'jmabel regard predomin scholari consensu allegedli claim despit third way rhetor fascism power function rather consist rightw forc far awar own numer book subject not scholari consensu consensu develop respect scholar fascism write manner not bia interest group roger griffin hamish mcdonald roger eatwel zeev sternhel recongis fascism third way refer show dissent awar seem think fascism absout leftist connect mere radic right system street level socialist want put much distanc movement possibl cours not come educ peopl posit write book exampl even foremost scholari expert fascism former member communist parti socialist parti itali renzo de felic nt tri cover socialist origin third way statu man wrote definit seven volum piec mussolini',
 'get fuck get fuckee got drink cant put get fuck get fuck fuck right',
 'thank undelet hope research statu texa govern includ local govern copyright statu slow go appar work florida govern usual public domain nt similar articl texa guess research oldfashion nonlazi actual reliabl way ask copyright help desk like suggest meantim use fair use rational sinc valid imag use articl thank',
 'stupid peac shit stop delet stuff asshol go die fall hole go hell',
 'toni sidaway obvious fistfucke love arm ass',
 'ga review ii sorri say fail articl gan sever major problem brought articl previou ga assess not issu said articl wplead longer histori media attent academ student govern demograph trivia addit inform section defici citiat also triva addit inform integr rest articl pleas look wpwiaga fix problem renomin gaclass howev reassess articl bclass meet bclass criteria regard']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
TV = TfidfVectorizer(min_df=2, max_features = 1000)   
X = TV.fit_transform(all_comments).toarray()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [ ]:
RF = RandomForestClassifier()
model1 = MultiOutputClassifier(estimator= RF)
model1.fit(X_train, y_train)

MultiOutputClassifier(estimator=RandomForestClassifier())

In [ ]:
list3 = Y.columns

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
pred = model1.predict(X_train)
print("Training Results")
for i in range(len(list3)):
    acc1 = accuracy_score(y_train.iloc[:, i], pred[:,i])
    print(list3[i] +':'+ str(acc1))

Training Results
toxic:0.9899763330084923
severe_toxic:0.9954336628149798
obscene:0.993846582207991
threat:0.9991090073785327
insult:0.9906724209940136
identity_hate:0.9975776138103857
Non-toxic:0.99022692468328

In [ ]:
pred1 = model1.predict(X_test)
print("Testing Results")
for i in range(len(list3)):
    acc2 = accuracy_score(y_test.iloc[:, i], pred1[:,i])
    print(list3[i]+ ': '+ str(acc2) )

Testing Results
toxic: 0.8815012807662324
severe_toxic: 0.9604633032631696
obscene: 0.9319523332219624
threat: 0.9904220960017819
insult: 0.8950885399264952
identity_hate: 0.9721572558191335
Non-toxic: 0.8877380554627464

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DAV_assignment/comment-toxicity-classification-ques /test.csv')
test.head()

                 id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [ ]:
test_comments = clean_text(test)
test_comments[0:20]

['yo bitch ja rule succes ever what hate sad mofuckasi bitch slap ur pethed white face get kiss ass guy sicken ja rule pride da music man dont diss shit nothin wrong bein like tupac brother toofuckin white boy get thing right next time',
 'rfc titl fine imo',
 'sourc zaw ashton lapland',
 'look back sourc inform updat correct form guess sourc nt updat shall updat inform thank messag',
 'nt anonym edit articl',
 'thank understand think highli would not revert without discuss',
 'pleas not add nonsens wikipedia edit consid vandal quickli undon would like experi pleas use sandbox instead thank',
 'dear god site horribl',
 'fool believ number correct number lie ponder number care error persist long time continu reproduc latest reproduct know encyclopædia britannica almanac wich state magnittud fair enough victim today not lot guess peopl come number impress enough nt know know shameless lucki number throw air gc',
 'doubl redirect fix doubl redirect nt blank outer one need edit point final target unless think inappropri case need nomin wprfd',
 'think crap link roggenbi articl somebodi know thing chang',
 'somebodi invari tri add religion realli mean way peopl invari kept ad religion samuel beckett infobox bother bring longdead complet nonexist influenc issu flail make crap fli comparison explicit acknowledg entir amo oz articl person jewish categori',
 'februari utc look clear ban sockpuppet ignor consensu fwiw policyappropri choic leav page chihuahua mexico current page return anyon time fix incom link',
 'say right type type institut need case three level suni school univers center doctor grant institut state colleg commun colleg need case clarifi ub suni center say even binghamton univers univers albani state univers new york stoni brook univers stop tri say not total right case',
 'ad new product list make sure relev ad new product list make sure wikipedia entri alreadi prove relev give reader possibl read otherwis could subject delet see articl revis histori',
 'current posit anyon confirm sir alfr longer airport hospitalis',
 'one',
 'reason ban throw articl need section throw ban moment noncricket fan seem kind arbitrari',
 'wallamoos chang cite materi say thing origin sourc not say respons object modifi articl went along not revert repeatedli ask use talk page tri add articl long time thin content wrong',
 'block edit wikipedia']

In [ ]:
X_t = TV.fit_transform(test_comments).toarray()

In [ ]:
pred_final = model1.predict(X_t)

In [ ]:
test_ans = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DAV_assignment/comment-toxicity-classification-ques /test_labels.csv')
test_ans.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1
1,0000247867823ef7,-1,-1,-1,-1,-1,-1
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1

In [ ]:
test_ans = test_ans.drop(columns = 'id')
test_ans.head()

   toxic  severe_toxic  obscene  threat  insult  identity_hate
0     -1            -1       -1      -1      -1             -1
1     -1            -1       -1      -1      -1             -1
2     -1            -1       -1      -1      -1             -1
3     -1            -1       -1      -1      -1             -1
4     -1            -1       -1      -1      -1             -1

In [ ]:
test_ans = test_ans.replace(-1, 1)
test_ans.head()

   toxic  severe_toxic  obscene  threat  insult  identity_hate
0      1             1        1       1       1              1
1      1             1        1       1       1              1
2      1             1        1       1       1              1
3      1             1        1       1       1              1
4      1             1        1       1       1              1

In [ ]:
for i in range(0, test_ans.shape[0]):
  if( (test_ans.loc[i, 'toxic'] == 0) & (test_ans.loc[i, 'severe_toxic'] == 0) & (test_ans.loc[i, 'obscene'] == 0) & (test_ans.loc[i, 'threat'] == 0) & (test_ans.loc[i, 'insult'] == 0) & (test_ans.loc[i, 'identity_hate'] == 0)):
    test_ans.loc[i, 'Non-toxic'] = 1
  else:
    test_ans.loc[i, 'Non-toxic'] = 0

In [ ]:
for i in range(len(list3)):
    acc3 = accuracy_score(test_ans.iloc[:, i], pred_final[:,i])
    print(list3[i]+ ': '+ str(acc3) )

toxic: 0.474302055313259
severe_toxic: 0.4153782873260035
obscene: 0.43141338695777076
threat: 0.4164229192238385
insult: 0.4228604632942467
identity_hate: 0.4137329920869134
Non-toxic: 0.4822216708887206

 There was a loss of lot of valuable voabulary / data while trying to remove bias. Hence the model is only giving 45% accuracy, still better as compared to the previous one.